# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(verbose_name='url')),
                ('status', models.SmallIntegerField(choices=[(1, 'Rozpocz\u0119ty'), (2, 'W trakcie'), (3, 'Zako\u0144czony')], default=1, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Strona',
                'verbose_name_plural': 'Strony',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=255, verbose_name='S\u0142owo')),
                ('count', models.IntegerField(default=0, verbose_name='Liczba wyst\u0105pie\u0144')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Page', verbose_name='Strona')),
            ],
            options={
                'verbose_name': 'S\u0142owo',
                'verbose_name_plural': 'S\u0142owa',
            },
        ),
    ]
