# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-28 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Rozpocz\u0119ty'), (2, 'W trakcie'), (3, 'Zako\u0144czony'), (4, 'Problem z po\u0142\u0105czeniem')], default=1, verbose_name='status'),
        ),
    ]
